# List Comprehensions Lab

Complete the following set of exercises to solidify your knowledge of list comprehensions.

In [1]:
import os
import numpy as np
import pandas as pd

### 1. Use a list comprehension to create and print a list of consecutive integers starting with 1 and ending with 50.

In [2]:
new_list=[i+1 for i in range(50)]

### 2. Use a list comprehension to create and print a list of even numbers starting with 2 and ending with 200.

In [3]:
new_list2=[i+2 for i in range(200) if i%2==0]

### 3. Use a list comprehension to create and print a list containing all elements of the 10 x 4 Numpy array below.

In [4]:
a = np.array([[0.84062117, 0.48006452, 0.7876326 , 0.77109654],
       [0.44409793, 0.09014516, 0.81835917, 0.87645456],
       [0.7066597 , 0.09610873, 0.41247947, 0.57433389],
       [0.29960807, 0.42315023, 0.34452557, 0.4751035 ],
       [0.17003563, 0.46843998, 0.92796258, 0.69814654],
       [0.41290051, 0.19561071, 0.16284783, 0.97016248],
       [0.71725408, 0.87702738, 0.31244595, 0.76615487],
       [0.20754036, 0.57871812, 0.07214068, 0.40356048],
       [0.12149553, 0.53222417, 0.9976855 , 0.12536346],
       [0.80930099, 0.50962849, 0.94555126, 0.33364763]])

In [8]:
new_list3 = [y for x in a for y in x]

### 4. Add a condition to the list comprehension above so that only values greater than or equal to 0.5 are printed.

In [14]:
new_list4 = [y for x in a for y in x if y >= 0.5]

### 5. Use a list comprehension to create and print a list containing all elements of the 5 x 2 x 3 Numpy array below.

In [6]:
b = np.array([[[0.55867166, 0.06210792, 0.08147297],
        [0.82579068, 0.91512478, 0.06833034]],

       [[0.05440634, 0.65857693, 0.30296619],
        [0.06769833, 0.96031863, 0.51293743]],

       [[0.09143215, 0.71893382, 0.45850679],
        [0.58256464, 0.59005654, 0.56266457]],

       [[0.71600294, 0.87392666, 0.11434044],
        [0.8694668 , 0.65669313, 0.10708681]],

       [[0.07529684, 0.46470767, 0.47984544],
        [0.65368638, 0.14901286, 0.23760688]]])

In [15]:
new_list5 = [z for x in b for y in x for z in y]
new_list5

[0.55867166,
 0.06210792,
 0.08147297,
 0.82579068,
 0.91512478,
 0.06833034,
 0.05440634,
 0.65857693,
 0.30296619,
 0.06769833,
 0.96031863,
 0.51293743,
 0.09143215,
 0.71893382,
 0.45850679,
 0.58256464,
 0.59005654,
 0.56266457,
 0.71600294,
 0.87392666,
 0.11434044,
 0.8694668,
 0.65669313,
 0.10708681,
 0.07529684,
 0.46470767,
 0.47984544,
 0.65368638,
 0.14901286,
 0.23760688]

### 5. Add a condition to the list comprehension above so that the last value in each subarray is printed, but only if it is less than or equal to 0.5.

In [34]:
new_list6 = [x[-1] for z in b for x in z if x[-1] <= 0.5]
#for z in b:
#    for x in z:
#            if x[-1] <= 0.5:
#                print (x[-1])
print(new_list6)

[0.08147297, 0.06833034, 0.30296619, 0.45850679, 0.11434044, 0.10708681, 0.47984544, 0.23760688]

### 6. Use a list comprehension to select and print the names of all CSV files in the */data* directory.

In [54]:
file_list = [file for file in os.listdir('../data') if file.endswith('.csv')]
file_list

['sample_file_6.csv',
 'sample_file_5.csv',
 'sample_file_3.csv',
 'sample_file_8.csv',
 'sample_file_1.csv',
 'sample_file_9.csv',
 'sample_file_0.csv',
 'sample_file_2.csv',
 'sample_file_4.csv',
 'sample_file_7.csv']

### 7. Use a list comprehension and the Pandas `read_csv` and `concat` methods to read all CSV files in the */data* directory and combine them into a single data frame. Display the top 10 rows of the resulting data frame.

In [40]:
data_sets = [pd.read_csv(os.path.join('../data', f)) for f in file_list]
data = pd.concat(data_sets, axis=0)
data.head(10)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0.702566,0.092336,0.245083,0.918402,0.695110,0.886921,0.588605,0.950970,0.168079,0.783107,0.698836,0.120857,0.207432,0.824789,0.349212,0.818606,0.376941,0.886644,0.472826,0.551858
1,0.177005,0.649551,0.467321,0.449597,0.458872,0.815586,0.455132,0.729812,0.998528,0.048724,0.377391,0.729498,0.721515,0.566724,0.338366,0.877239,0.129824,0.773155,0.485385,0.686294
2,0.689556,0.445586,0.005691,0.150171,0.554146,0.492320,0.185612,0.060855,0.457443,0.847337,0.603072,0.346574,0.898464,0.482963,0.443979,0.430132,0.713078,0.302786,0.051382,0.203699
3,0.047188,0.854596,0.833368,0.043878,0.883505,0.786302,0.980916,0.004030,0.619601,0.547769,0.160962,0.545281,0.931623,0.991855,0.821099,0.654592,0.346710,0.183948,0.372739,0.739383
4,0.936065,0.725831,0.184239,0.677391,0.242726,0.125457,0.356254,0.937350,0.215774,0.212762,0.483018,0.573162,0.634487,0.423924,0.394633,0.766967,0.606719,0.538712,0.885516,0.667051
0,0.437114,0.156941,0.183148,0.817785,0.747632,0.726855,0.944758,0.287449,0.792692,0.080025,0.079886,0.067887,0.543498,0.711158,0.960030,0.810807,0.579395,0.660811,0.520295,0.945250
1,0.213337,0.503490,0.802663,0.443484,0.700893,0.129329,0.007176,0.027735,0.427692,0.156926,0.486138,0.571278,0.940414,0.940730,0.933377,0.427869,0.654402,0.407580,0.122453,0.115311
2,0.625692,0.184609,0.120652,0.410955,0.408272,0.686792,0.480168,0.286901,0.320112,0.048815,0.768725,0.461014,0.090451,0.720938,0.192501,0.219077,0.034113,0.858956,0.816036,0.582192
3,0.642007,0.175592,0.476889,0.451096,0.803491,0.272613,0.576037,0.774269,0.323313,0.349850,0.413465,0.641111,0.841210,0.668661,0.101031,0.972135,0.479581,0.149982,0.035150,0.528075
4,0.809129,0.549374,0.055405,0.857802,0.760688,0.662257,0.453289,0.658329,0.973615,0.449771,0.615229,0.467290,0.158077,0.305716,0.730355,0.412336,0.469142,0.078734,0.448741,0.827487

### 8. Use a list comprehension to select and print the column numbers for columns from the data set whose median is less than 0.48.

In [63]:
#selected_columns = [col for col in data._get_numeric_data() if data[col].median() < 0.48]
selected_columns = [ncol for ncol in data if data[str(ncol)].median() < 0.48]

selected_columns

['2', '9', '12', '14', '17']

### 9. Use a list comprehension to add a new column (20) to the data frame whose values are the values in column 19 minus 0.1. Display the top 10 rows of the resulting data frame.

In [71]:
lista = [n-0.1 for n in data["19"]]
data[20]= lista
data.head(10)

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,0.702566,0.092336,0.245083,0.918402,0.695110,0.886921,0.588605,0.950970,0.168079,0.783107,...,0.120857,0.207432,0.824789,0.349212,0.818606,0.376941,0.886644,0.472826,0.551858,0.451858
1,0.177005,0.649551,0.467321,0.449597,0.458872,0.815586,0.455132,0.729812,0.998528,0.048724,...,0.729498,0.721515,0.566724,0.338366,0.877239,0.129824,0.773155,0.485385,0.686294,0.586294
2,0.689556,0.445586,0.005691,0.150171,0.554146,0.492320,0.185612,0.060855,0.457443,0.847337,...,0.346574,0.898464,0.482963,0.443979,0.430132,0.713078,0.302786,0.051382,0.203699,0.103699
3,0.047188,0.854596,0.833368,0.043878,0.883505,0.786302,0.980916,0.004030,0.619601,0.547769,...,0.545281,0.931623,0.991855,0.821099,0.654592,0.346710,0.183948,0.372739,0.739383,0.639383
4,0.936065,0.725831,0.184239,0.677391,0.242726,0.125457,0.356254,0.937350,0.215774,0.212762,...,0.573162,0.634487,0.423924,0.394633,0.766967,0.606719,0.538712,0.885516,0.667051,0.567051
0,0.437114,0.156941,0.183148,0.817785,0.747632,0.726855,0.944758,0.287449,0.792692,0.080025,...,0.067887,0.543498,0.711158,0.960030,0.810807,0.579395,0.660811,0.520295,0.945250,0.845250
1,0.213337,0.503490,0.802663,0.443484,0.700893,0.129329,0.007176,0.027735,0.427692,0.156926,...,0.571278,0.940414,0.940730,0.933377,0.427869,0.654402,0.407580,0.122453,0.115311,0.015311
2,0.625692,0.184609,0.120652,0.410955,0.408272,0.686792,0.480168,0.286901,0.320112,0.048815,...,0.461014,0.090451,0.720938,0.192501,0.219077,0.034113,0.858956,0.816036,0.582192,0.482192
3,0.642007,0.175592,0.476889,0.451096,0.803491,0.272613,0.576037,0.774269,0.323313,0.349850,...,0.641111,0.841210,0.668661,0.101031,0.972135,0.479581,0.149982,0.035150,0.528075,0.428075
4,0.809129,0.549374,0.055405,0.857802,0.760688,0.662257,0.453289,0.658329,0.973615,0.449771,...,0.467290,0.158077,0.305716,0.730355,0.412336,0.469142,0.078734,0.448741,0.827487,0.727487

### 10. Use a list comprehension to extract and print all values from the data set that are between 0.7 and 0.75.

In [96]:
list10 = [y for x in data for y in data[x] if y > 0.7 and y < 0.75]
#list10 = []
#for x in data:
#    for y in data[x]:
#        if y > 0.7 and y< 0.75:
#            list10.append(y)
list10

[0.7025657075988269,
 0.7132714209987683,
 0.7280006345208285,
 0.7347510852128797,
 0.7258310816144985,
 0.736029494090402,
 0.7472962776291713,
 0.7343092314001137,
 0.7088042362916818,
 0.7358941798147411,
 0.7365416322783028,
 0.7023481768180954,
 0.7329024831531535,
 0.7476323136755818,
 0.7008930873050235,
 0.7133695725698419,
 0.7268545088531969,
 0.7032248108904495,
 0.7357618655811269,
 0.7150799992177622,
 0.7173964318670598,
 0.7013619954419494,
 0.7306642125209889,
 0.7383982036983279,
 0.7124169515124726,
 0.71223975981198,
 0.7298115760258881,
 0.7051334608870933,
 0.7321333453970806,
 0.7178166705957928,
 0.7374449181749492,
 0.7159290265157912,
 0.7294980584878026,
 0.7215147068185102,
 0.7111584953876777,
 0.7209375615129192,
 0.7045750112959754,
 0.7303553716733908,
 0.7133690799930356,
 0.7396561066717461,
 0.7078738356977186,
 0.7321533684342264,
 0.7356923324968598,
 0.7390312927111312,
 0.7130781095091867,
 0.7490680818183477,
 0.7085098152301276,
 0.7196096371031628,
 0.7264121114538001,
 0.7393833032570581,
 0.7244863338885654,
 0.7274869207330491,
 0.7376946446827494,
 0.7033930409580709]